language: ruby

sudo: false

cache: bundler

addons:
  apt:
    packages:
      - libtokyocabinet-dev
      - tokyocabinet-bin

before_install:
  - gem install bundler

env:
  matrix:
    - STORAGE=sqlite3
    - STORAGE=dbm
    - STORAGE=groonga
    - OPTIONAL=yes

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4
  - ruby-head

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: OPTIONAL=yes
